### ISSUE TITLE
Application crashes on Windows 10

### ISSUE THREAD

**Issue by ADHaddock** [KoenZomers/RingRecordingDownload#9]
Hello,

There is a strong chance that I am doing this wrong as I am new to this. However I have downloaded your latest version of the application for what I believe is the correct version of windows. However when I attempt to run the application it loads up CMD.exe before closing it again less than half a second later. Would you know what might be causing this?

Thanks,

Adam

**Comment by KoenZomers** [comment]
Hi @ADHaddock, it's a console application, so that's normal. For Windows, just download this version:
https://github.com/KoenZomers/RingRecordingDownload/releases/download/2.0.2.1/win-x64-full.zip

Extract it anywhere on your system, hit the Windows key + R on your keyboard, type cmd and hit enter. Browse to the folder where you extracted the files and run ```RingRecordingDownload.exe```. It will show you all the possible command line options to use this tool.

![image](https://user-images.githubusercontent.com/5940670/106535814-5888eb80-64f7-11eb-8ce8-5024a0ea13b6.png)

**Comment by KoenZomers** [comment]
Closing the issue as no further feedback has been received. Feel free to reopen in case it's still not working well for you.
